# -*- coding: utf-8 -*-
"""4th-march-assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ja8BWGN8gnXyMDznefT7GJV4aLtBHw8x
"""

import plotly.graph_objects as go
import pandas as pd
import numpy as np
import seaborn as sns

Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a
scatter plot for age and fare columns in the titanic dataset.

"""Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a
scatter plot for age and fare columns in the titanic dataset.
"""

import plotly.express as px
import pandas as pd
import numpy as np
import seaborn as sn

titanic=sns.load_dataset('titanic')
titanic.head()

fig = px.scatter(titanic, x="age", y="fare", title="Age Vs Fare")
fig.show()

"""Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express."""

import plotly.express as px
tips = px.data.tips()
tips.head()

fig = px.box(tips, x='day',y="total_bill")
fig.show()

"""Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in
the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day"
column with the color parameter.
"""

import plotly.express as px
tips = px.data.tips()
tips.head()

fig = px.histogram(tips, x='sex',y="total_bill",pattern_shape='smoker',color='day')
fig.show()

"""Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for
the color parameter.
Note: Use "sepal_length", "sepal_width", "petal_length", "petal_width" columns only with the
dimensions parameter.
"""

import plotly.express as px
iris = px.data.iris()
iris.head()

fig = px.scatter_matrix(iris,dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"],color='species')
fig.show()

"""Q5. What is Distplot? Using Plotly express, plot a distplot.

Ans :

Distplots are used for univariant analysis on a continuous or numerical data.
Displots are the combination of 3 graphs :
1. Histogram
2. KDE(Kernal Density Estimation) plot
3. RugPlot
"""

Distplots are used for univariant analysis on a continuous or numerical data.
Displots are the combination of 3 graphs :
1. Histogram
2. KDE(Kernal Density Estimation) plot
3. RugPlot

import plotly.figure_factory as ff
import seaborn as sns
titanic= sns.load_dataset('titanic')
titanic.head()

titanic['age'].fillna(titanic['age'].mean(),inplace=True)

hist_data=[titanic[titanic['survived']==1]['age'],titanic[titanic['survived']==0]['age']]
group_labels = ["Survived", "Not Survived"]
fig = ff.create_distplot(hist_data,
                         group_labels)

fig.show()

group_labels = ["Not survived"])
fig.show()

